baseurl = "https://EvolveFromWithin.github.io"
languageCode = "en-us"
title = "Evolve From Within: Techniques for Discovery"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	description = "Techniques for Discovery"

	logo = "/images/wtf-web.jpg"
	favicon = "images/wtf-favicon-96.ico"
	banner_image = "/images/WinterTechForumBanner.png"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "indigo"
    	accent  = "red"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "EvolveFromWithin"
	email   = "mindviewinc@gmail.com"

[[menu.main]]
	name   = "Techniques"
	url    = "/"
	weight = 10



[[menu.main]]
	name   = "Contact"
	url    = "contact/"
	weight = 100


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
